version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./src/module/${MODULE}/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sandbox"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: nodejs-modular-monolith
    build:
      context: ./
    image: nodejs-modular-monolith
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - ./.env
    links:
      - db
